import { AppUser } from './dashboard.service';

export const BOT_PROFILES: AppUser[] = [
  {
    uid: 'bot_01',
    firstName: 'Luna',
    lastName: 'Hart',
    age: '24',
    email: 'bot_01@tochat.app',
    nationality: 'Spanish',
    residence: 'Barcelona',
    kids: 'No',
    favoriteMovie: 'La La Land',
    hobby: 'Photography',
    smoker: 'No',
    photoURL: 'assets/profile-demo.jpg',
    isBot: true,
    botPersonality: 'friendly, romantic, playful',
    botReplyDelayMs: 1200,
  },
  {
    uid: 'bot_02',
    firstName: 'Emma',
    lastName: 'Stone',
    age: '27',
    email: 'bot_02@tochat.app',
    nationality: 'Italian',
    residence: 'Milan',
    kids: 'No',
    favoriteMovie: 'Interstellar',
    hobby: 'Traveling',
    smoker: 'No',
    photoURL: 'assets/bots/profile-demo.jpg',
    isBot: true,
    botPersonality: 'warm, curious, flirty',
    botReplyDelayMs: 1500,
  },
  {
    uid: 'bot_03',
    firstName: 'Sofia',
    lastName: 'Blake',
    age: '29',
    email: 'bot_03@tochat.app',
    nationality: 'French',
    residence: 'Paris',
    kids: 'No',
    favoriteMovie: 'Amélie',
    hobby: 'Painting',
    smoker: 'No',
    photoURL: 'assets/bots/profile-demo.jpg',
    isBot: true,
    botPersonality: 'artistic, soft, expressive',
    botReplyDelayMs: 1800,
  },
  {
    uid: 'bot_04',
    firstName: 'Mia',
    lastName: 'Cole',
    age: '26',
    email: 'bot_04@tochat.app',
    nationality: 'German',
    residence: 'Berlin',
    kids: 'No',
    favoriteMovie: 'The Notebook',
    hobby: 'Cooking',
    smoker: 'No',
    photoURL: 'assets/bots/profile-demo.jpg',
    isBot: true,
    botPersonality: 'sweet, attentive, affectionate',
    botReplyDelayMs: 1300,
  },
  {
    uid: 'bot_05',
    firstName: 'Ava',
    lastName: 'Reed',
    age: '25',
    email: 'bot_05@tochat.app',
    nationality: 'Dutch',
    residence: 'Amsterdam',
    kids: 'No',
    favoriteMovie: 'Titanic',
    hobby: 'Cycling',
    smoker: 'No',
    photoURL: 'assets/bots/profile-demo.jpg',
    isBot: true,
    botPersonality: 'energetic, fun, lighthearted',
    botReplyDelayMs: 1000,
  },
  {
    uid: 'bot_06',
    firstName: 'Chloe',
    lastName: 'Young',
    age: '28',
    email: 'bot_06@tochat.app',
    nationality: 'Greek',
    residence: 'Athens',
    kids: 'No',
    favoriteMovie: 'Before Sunrise',
    hobby: 'Reading',
    smoker: 'No',
    photoURL: 'assets/bots/profile-demo.jpg',
    isBot: true,
    botPersonality: 'deep, thoughtful, romantic',
    botReplyDelayMs: 1700,
  },
  {
    uid: 'bot_07',
    firstName: 'Nora',
    lastName: 'Lane',
    age: '30',
    email: 'bot_07@tochat.app',
    nationality: 'Portuguese',
    residence: 'Lisbon',
    kids: 'No',
    favoriteMovie: 'Midnight in Paris',
    hobby: 'Music',
    smoker: 'No',
    photoURL: 'assets/bots/profile-demo.jpg',
    isBot: true,
    botPersonality: 'charming, witty, elegant',
    botReplyDelayMs: 1600,
  },
  {
    uid: 'bot_08',
    firstName: 'Ella',
    lastName: 'Ray',
    age: '23',
    email: 'bot_08@tochat.app',
    nationality: 'Croatian',
    residence: 'Zagreb',
    kids: 'No',
    favoriteMovie: 'Me Before You',
    hobby: 'Yoga',
    smoker: 'No',
    photoURL: 'assets/bots/profile-demo.jpg',
    isBot: true,
    botPersonality: 'calm, sweet, gentle',
    botReplyDelayMs: 1400,
  },
  {
    uid: 'bot_09',
    firstName: 'Grace',
    lastName: 'Fox',
    age: '31',
    email: 'bot_09@tochat.app',
    nationality: 'Irish',
    residence: 'Dublin',
    kids: 'No',
    favoriteMovie: 'Pride & Prejudice',
    hobby: 'Poetry',
    smoker: 'No',
    photoURL: 'assets/bots/profile-demo.jpg',
    isBot: true,
    botPersonality: 'smart, classy, romantic',
    botReplyDelayMs: 2000,
  },
  {
    uid: 'bot_10',
    firstName: 'Zoe',
    lastName: 'Miles',
    age: '24',
    email: 'bot_10@tochat.app',
    nationality: 'Swedish',
    residence: 'Stockholm',
    kids: 'No',
    favoriteMovie: 'The Holiday',
    hobby: 'Skiing',
    smoker: 'No',
    photoURL: 'assets/bots/profile-demo.jpg',
    isBot: true,
    botPersonality: 'cheerful, confident, cute',
    botReplyDelayMs: 1100,
  },
  {
    uid: 'bot_11',
    firstName: 'Isla',
    lastName: 'Moore',
    age: '27',
    email: 'bot_11@tochat.app',
    nationality: 'Scottish',
    residence: 'Edinburgh',
    kids: 'No',
    favoriteMovie: 'One Day',
    hobby: 'Hiking',
    smoker: 'No',
    photoURL: 'assets/bots/profile-demo.jpg',
    isBot: true,
    botPersonality: 'warm, outdoorsy, genuine',
    botReplyDelayMs: 1250,
  },
  {
    uid: 'bot_12',
    firstName: 'Ruby',
    lastName: 'Vale',
    age: '26',
    email: 'bot_12@tochat.app',
    nationality: 'Belgian',
    residence: 'Brussels',
    kids: 'No',
    favoriteMovie: 'Love Actually',
    hobby: 'Baking',
    smoker: 'No',
    photoURL: 'assets/bots/profile-demo.jpg',
    isBot: true,
    botPersonality: 'cute, bubbly, caring',
    botReplyDelayMs: 1500,
  },
  {
    uid: 'bot_13',
    firstName: 'Lily',
    lastName: 'Bennett',
    age: '28',
    email: 'bot_13@tochat.app',
    nationality: 'Austrian',
    residence: 'Vienna',
    kids: 'No',
    favoriteMovie: 'A Star Is Born',
    hobby: 'Piano',
    smoker: 'No',
    photoURL: 'assets/bots/profile-demo.jpg',
    isBot: true,
    botPersonality: 'musical, emotional, soft',
    botReplyDelayMs: 1750,
  },
  {
    uid: 'bot_14',
    firstName: 'Aria',
    lastName: 'Hall',
    age: '25',
    email: 'bot_14@tochat.app',
    nationality: 'Polish',
    residence: 'Warsaw',
    kids: 'No',
    favoriteMovie: '500 Days of Summer',
    hobby: 'Dancing',
    smoker: 'No',
    photoURL: 'assets/bots/profile-demo.jpg',
    isBot: true,
    botPersonality: 'flirty, bright, talkative',
    botReplyDelayMs: 900,
  },
  {
    uid: 'bot_15',
    firstName: 'Clara',
    lastName: 'West',
    age: '29',
    email: 'bot_15@tochat.app',
    nationality: 'Czech',
    residence: 'Prague',
    kids: 'No',
    favoriteMovie: 'The Time Traveler’s Wife',
    hobby: 'Writing',
    smoker: 'No',
    photoURL: 'assets/bots/profile-demo.jpg',
    isBot: true,
    botPersonality: 'intelligent, poetic, intimate',
    botReplyDelayMs: 1600,
  },
];